### ISSUE TITLE
Add yourself to the README.md

### ISSUE THREAD

**Issue by lapinell** [nashvillefcc/local-weather-app#10]
**User Story**
The user, a visitor to our repo, should be able to find a list of team members so that they can determine who was on the original Local Web App team.

**Acceptance Criteria**

- [x]  The user should be able to find a section called "Team Members"
- [x] The user should be able to find each team members name
- [x] The user should be able to determine whether the team member contributed as a designer, developer or other.
- [x] The user should be able to click on the team member name and be redirected to their github profile.

**Notes** 
Multiple team members will be working on the same file. You need to work together to determine who will create what so their are as few conflicts as possible.

**Comment by mgaytan** [comment]
I went ahead and added a "Team Members" section in the readme so everyone who is contributing can add their name to it.
