### ISSUE TITLE
Display Weather Icon

### ISSUE THREAD

**Issue by lapinell** [nashvillefcc/local-weather-app#16]
This issue is part of #3 Display Current Weather

**User Story**
As an app user, I want to be able to see the weather icon so that I can see at a glance what the weather is.

**Acceptance Criteria**
- [ ] User should be able to see an weather icon
- [ ] User should see the weather icon as the forth section on the page
- [ ] Use semantic HTML
- [ ] Use a unique ID
- [ ] Use mobile-first styling

**Comment by jhadams82** [comment]
Is this another issue that should still be open? We're not showing a weather icon yet, that's the task I just assigned myself.
